apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend #Chọn Pods nào để route traffic
  ports:
  - protocol: TCP
    port: 80 #Port của Service
    targetPort: 3000 #Port của Container
